### ISSUE TITLE
Поработать с ветками

### ISSUE THREAD

**Issue by akaspat** [dimario9122/carServiceProject#1]
* От ветки master (main) создать ветку test  
* Закоммитить на ветку test любой код работы с flask
* Запушить изменения
* Выполнить merge-request в master (main)

**Comment by dimario9122** [comment]
Проблемка с merge

**Comment by akaspat** [comment]
@dimario9122 , выше нашей переписки - список действий, справа есть id коммита:
например: 
коммит: 
Revert "Revert "Revert "Revert "Merge #1""""  имеет id 0e7d1fc . 
Все было сделано верно на коммите с id 310a9db . 
Дальнейшие действия были не нужны.
