### ISSUE TITLE
Создать .gitignore

### ISSUE THREAD

**Issue by akaspat** [dimario9122/carServiceProject#4]
* узнать для чего нужен этот файл  
* сформировать gitignore c помощью `gitignore.io`

**Comment by dimario9122** [comment]
mission completed

**Comment by akaspat** [comment]
@dimario9122 переименовала файл в .gitignore
`.gitignore служит для указания в нём файлов и папок, которые необходимо скрыть от системы контроля версий git.`
gitignore - это не расширение, а название файла. Точка в начале говорит о том, что файл является скрытым.
мини шпаргалка: [gitignore](http://orlov.io/ru/articles/podrobnee-o-faile-gitignore)
