### ISSUE TITLE
Решить по поводу Fast API

### ISSUE THREAD

**Issue by akaspat** [dimario9122/carServiceProject#8]

**Comment by akaspat** [comment]
@bashtblrkin отпишись сюда пожалуйста - насколько сильно мы выйграем по "удобству" перенеся с Flask на FastAPI. Хоть кода написано и немного, но переносить честно говоря, чуть-чуть лень и закрыдывается вопрос: может допилим наш мини-проект на Flask?
Помоги мне в раздумьях. пожалуйста)

**Comment by bashtblrkin** [comment]
@akaspat можем обойтись без FastAPI, почитав информацию о Flask, я понял, что нам это будет необязательно, поскольку там не будет явных ajax запросов как это пишется в нативном js. Придётся поучить Flask, но так даже интереснее!

**Comment by akaspat** [comment]
@bashtblrkin , отлично! Тогда оставляем Flask, а с нас с димасом - отличные комментарии (и да, документирование кода .. я сделаю его когда нибудь уже), что б тебе было комфортно читать и сразу понимать о чем речь)
