### ISSUE TITLE
Заполнить БД данными

### ISSUE THREAD

**Issue by akaspat** [dimario9122/carServiceProject#9]
Заполнить таблицу "Авто":

* марка авто (Trademark)
* модель авто (Model)

Заполнить таблицу "Услуга":

* тип услуги (about)

Заполнить таблицу "Услуга-авто" имея предыдущие данные

### Схема базы данных
![db_cxem](https://user-images.githubusercontent.com/47475836/99563750-a1420580-29da-11eb-943f-2fd5b08206c4.png)

**Comment by dimario9122** [comment]
Uploaded the completed database with the project to the branch fullDataBase
